// errors.js

module.exports = {
    invalidDateFormat: 'Invalid date format for "day"',
    invalidEmployeeId: '"employeeId" must be a string',
    leaveNotFound: 'Could not find leave for the provided day and employeeId',
    holidayNotFound: 'Could not find holiday for the provided day',
    retrieveLeaveError: 'Could not retrieve leave',
    retrieveHolidayError: 'Could not retrieve holiday',
    createHolidayError: 'Could not create holiday',
    retrieveAllHolidaysError: 'Could not retrieve all holidays',
    noLeavesFound: 'No leaves found',
    retrieveAllLeavesError: 'Could not retrieve all leaves',
    createLeaveError: 'Could not create leave',
    invalidInputData: 'Invalid input data',
    userNotFound: 'Could not find user with provided "userId"',
    updateUserError: 'Could not update user',
    getEmployeePersonsError: 'Could not get employee persons',
    getSupervisorPersonsError: 'Could not get supervisor persons',
    getHRPersonsError: 'Could not get HR persons',
    createUserError: 'Could not create user',
    companyNotFound: 'Company not found with the provided companyId',
    createCompanyError: 'Could not create company',
    createAdminError: 'Could not create admin',
    invalidCredentials: 'Invalid email or password.',
    getUsersError: 'Could not get users',
    adminInfoNotFound: 'Admin information not found or missing companyId',
    adminCompanyInfoNotFound: 'Admin information not found or missing companyId',
  };
  