service: AMS-Project
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ AdminsTable, Arn ]
            - Fn::GetAtt: [ EmployeesTable, Arn ]
            - Fn::GetAtt: [ HolidayCalendar, Arn ]
            - Fn::GetAtt: [ LeavesCalendar, Arn ]
            - Fn::GetAtt: [ CompanyTable, Arn ]
            - Fn::GetAtt: [ TeamTable, Arn ]
            - Fn::GetAtt: [ AttendanceTable, Arn ]
  environment:
    EMPLOYEES_TABLE: ${self:custom.employeesTableName}
    ADMINS_TABLE: ${self:custom.adminsTableName}
    HOLIDAY_CALENDAR_TABLE: ${self:custom.holidayCalendarTableName}
    LEAVES_CALENDAR_TABLE: ${self:custom.leavesCalendarTableName}
    COMPANY_TABLE: ${self:custom.companyTableName}
    TEAM_TABLE: ${self:custom.teamTableName}
    ATTENDANCE_TABLE: ${self:custom.attendanceTableName}
    
custom:
  adminsTableName: admins
  employeesTableName: employees
  holidayCalendarTableName: holidayCalender
  leavesCalendarTableName: leavesCalender
  companyTableName: company
  teamTableName: team
  attendanceTableName: attendance

resources:
  Resources:
    AdminsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.adminsTableName}

    EmployeesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.employeesTableName}

    HolidayCalendar:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: Day
            AttributeType: S
        KeySchema:
          - AttributeName: Day
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.holidayCalendarTableName}

    LeavesCalendar:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: Day
            AttributeType: S
          - AttributeName: EmployeeId
            AttributeType: S
        KeySchema:
          - AttributeName: Day
            KeyType: HASH
          - AttributeName: EmployeeId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.leavesCalendarTableName}

    CompanyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: companyId
            AttributeType: S
        KeySchema:
          - AttributeName: companyId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.companyTableName}

    TeamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.teamTableName}

    AttendanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
          - AttributeName: attendanceId
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: attendanceId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.attendanceTableName}
