module.exports = {
  adminCompanyInfoNotFound: 'Admin information not found or missing companyId',
  adminInfoNotFound: 'Admin information not found or missing companyId',
  alreadyCheckedIn: 'You are already checked in',
  alreadyCheckedOut: 'You are already checked out',
  attendanceRecordNotFound: 'Attendance record not found',
  companyNotFound: 'Company not found with the provided companyId',
  createAdminError: 'Could not create admin',
  createCompanyError: 'Could not create company',
  createHolidayError: 'Could not create holiday',
  createLeaveError: 'Could not create leave',
  createUserError: 'Could not create user',
  getEmployeePersonsError: 'Could not get employee persons',
  getHRPersonsError: 'Could not get HR persons',
  getSupervisorPersonsError: 'Could not get supervisor persons',
  getUsersError: 'Could not get users',
  holidayNotFound: 'Could not find holiday for the provided day',
  imageUploadError: 'Error uploading image',
  invalidCredentials: 'Invalid email or password.',
  invalidDateFormat: 'Invalid date format for "day"',
  invalidEmployeeId: '"employeeId" must be a string',
  invalidInputData: 'Invalid input data',
  leaveNotFound: 'Could not find leave for the provided day and employeeId',
  markAttendanceError: 'Could not mark attendance',
  noLeavesFound: 'No leaves found',
  previousCheckInNotFound: 'Cannot mark check-out without a previous check-in for the day',
  retrieveAllHolidaysError: 'Could not retrieve all holidays',
  retrieveAllLeavesError: 'Could not retrieve all leaves',
  retrieveAttendanceError: 'Error fetching attendance details',
  retrieveHolidayError: 'Could not retrieve holiday',
  retrieveLeaveError: 'Could not retrieve leave',
  updateCompanyError: 'Could not update company',
  updateUserError: 'Could not update user',
  userNotFound: 'Could not find user with provided "userId"',
  userWithinRadiusError: 'Error checking if the user is within the radius'
};
